### PR TITLE
Update agy_public_script.js

### PR DESCRIPTION
**Pull request by Maugrey**
Adding path=/ in the cookie to make the age verification to the whole site.

### CODE REVIEW

**Comment by mradulovic988** [comment]
@Maugrey How do you mean to make it for the whole website?

**Comment by Maugrey** [comment]
If you are coming to the website in a sub directory, the cookie will be put for this subdirectory only. So, is you then go to the root, the verification will be asked again.
Example : 
Go to http://www.domain.com/subfolder/ and accept the age verification.
The path of the cookie is automatically set to "/subfolder/".
Then if you go to http://www.domain.com/, the cookie is not found (because it was set on /subfolder/), so the age verification is displayed again.
Same problem if you to to http://www.domain.com/subfolder2/

But if you force the path to "/" when the cookie is set, it will be applied to the whole domain, no matters where the age verification was accepted.

**Comment by mradulovic988** [comment]
That makes sense. GIve me a few days to test that, since I'm busy currently.

**Comment by mradulovic988** [comment]
It's good. Do you want me to add you as a contributor to the next plugin release? If so, please send me the nick from the wordpress.org

**Pull request merged**
